from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

from .llm import generate_plan_json, llm_enabled
from .schemas import PlanStep, RunRequest, WorkflowPlan


def _contains_any(query: str, keywords: List[str]) -> bool:
    q = query.lower()
    return any(word in q for word in keywords)


def _normalize_emails(recipients: List[str], query: str) -> List[str]:
    found = re.findall(r"[\w\.-]+@[\w\.-]+\.\w+", query)
    merged = list(dict.fromkeys(recipients + found))
    return merged


async def build_plan(request: RunRequest, upload_meta: Optional[Dict[str, Any]]) -> WorkflowPlan:
    if llm_enabled():
        llm_plan = await _try_llm_plan(request, upload_meta)
        if llm_plan:
            return llm_plan

    return _rule_plan(request, upload_meta)


async def _try_llm_plan(request: RunRequest, upload_meta: Optional[Dict[str, Any]]) -> Optional[WorkflowPlan]:
    prompt = (
        f"User query: {request.query}\n"
        f"Mode: {request.mode.value}\n"
        f"Recipients: {request.recipients}\n"
        f"Has CSV upload: {bool(upload_meta)}\n"
        f"CSV columns: {upload_meta['columns'] if upload_meta else []}\n"
        f"Context text provided: {bool(request.context_text)}\n"
        "Available tools: analyze_csv, summarize_text, draft_email, send_email, schedule_meeting.\n"
        "Build the best multi-step workflow plan."
    )
    try:
        raw = await generate_plan_json(prompt)
        if not raw:
            return None
        steps = [PlanStep(**step) for step in raw.get("steps", [])]
        return WorkflowPlan(
            planner_source="llm",
            summary=raw.get("summary", "Generated by LLM planner."),
            steps=steps,
            warnings=raw.get("warnings", []),
        )
    except Exception:
        return None


def _rule_plan(request: RunRequest, upload_meta: Optional[Dict[str, Any]]) -> WorkflowPlan:
    query = request.query.strip()
    recipients = _normalize_emails(request.recipients, query)

    wants_csv = upload_meta is not None or _contains_any(
        query, ["csv", "spreadsheet", "analyze", "trend", "dataset", "data"]
    )
    wants_summary = bool(request.context_text) or _contains_any(
        query, ["summarize", "summary", "report", "recap", "findings"]
    )
    wants_email = _contains_any(query, ["email", "mail", "send"])
    wants_meeting = _contains_any(query, ["schedule", "meeting", "calendar", "tomorrow", "afternoon"])

    steps: List[PlanStep] = []
    warnings: List[str] = []

    if wants_csv:
        if upload_meta is None:
            warnings.append("The request suggests CSV analysis, but no CSV file was uploaded.")
        steps.append(
            PlanStep(
                id="step_analyze_csv",
                title="Analyze uploaded CSV",
                tool_name="analyze_csv",
                reason="The user asked for trends or analysis on data.",
                args={"file_path": upload_meta["path"] if upload_meta else None},
            )
        )

    if wants_summary or wants_email:
        summary_source = "context_text" if request.context_text else "previous_output"
        steps.append(
            PlanStep(
                id="step_summarize",
                title="Summarize key findings",
                tool_name="summarize_text",
                reason="A concise summary helps downstream communication and explainability.",
                depends_on=["step_analyze_csv"] if wants_csv else [],
                args={"source": summary_source},
            )
        )

    if wants_email:
        steps.append(
            PlanStep(
                id="step_draft_email",
                title="Draft summary email",
                tool_name="draft_email",
                reason="The request includes an email action.",
                depends_on=["step_summarize"] if (wants_summary or wants_email) else [],
                args={"recipients": recipients},
            )
        )
        steps.append(
            PlanStep(
                id="step_send_email",
                title="Send or simulate email delivery",
                tool_name="send_email",
                reason="This completes the communication task.",
                depends_on=["step_draft_email"],
                args={},
                confirmation_required=request.mode.value == "live",
            )
        )

    if wants_meeting:
        steps.append(
            PlanStep(
                id="step_schedule_meeting",
                title="Schedule or simulate a meeting",
                tool_name="schedule_meeting",
                reason="The request includes a calendar task.",
                depends_on=[],
                args={"query": query, "recipients": recipients},
                confirmation_required=request.mode.value == "live",
            )
        )

    if not steps:
        steps.append(
            PlanStep(
                id="step_summarize",
                title="Summarize the request and context",
                tool_name="summarize_text",
                reason="Fallback step so the agent remains useful even when the request is vague.",
                args={"source": "query"},
            )
        )
        warnings.append("The planner fell back to a simple summarization workflow.")

    return WorkflowPlan(
        planner_source="rules",
        summary="A reliability-first rule planner translated the request into typed workflow steps.",
        steps=steps,
        warnings=warnings,
    )
